---
name: secure_af
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.2+4
  cupertino_icons: ^1.0.2
  sqflite: ^1.3.2+4
  http: ^0.13.1
  url_launcher: ^6.0.2
  shared_preferences: ^0.5.12+4
  font_awesome_flutter: ^8.12.0
  flutter_launcher_icons: "^0.7.0"
dependency_overrides:
  shared_preferences:
    git:
      url: https://github.com/Flutter-Dart-Open-Source/plugins.git
      path: packages/shared_preferences/shared_preferences
      ref: update_prefs
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - assets/images/
  fonts:
  - family: Pacifico
    fonts:
    - asset: assets/fonts/Pacifico-Regular.ttf
  - family: Source Sans Pro
    fonts:
    - asset: assets/fonts/SourceSansPro-Regular.ttf
flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon_bg.png"
  image_path_android: "assets/launcher/icon_bg.png"
  adaptive_icon_background: "assets/launcher/icon_bg.png"
  adaptive_icon_foreground: "assets/launcher/icon1.png"

